# Install required plugins
required_plugins = %w( vagrant-hostsupdater vagrant-berkshelf )
required_plugins.each do |plugin|
 exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
  config.vm.define "nginx" do |ng|
    ng.vm.box = "ubuntu/xenial64"
    ng.vm.network "private_network", ip: "192.168.10.100"
    ng.hostsupdater.aliases = ["development.local"]
    ng.vm.synced_folder "Uber_app", "/home/ubuntu/Uber_app"
end
